name: Bug Report
description: Report a bug or unexpected behavior.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Minimal steps to reproduce the behavior.
      placeholder: |
        1. Install the package with `uv sync`
        2. Run `...`
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or tracebacks.
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`.
      placeholder: "3.12.0"
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "Ubuntu 22.04 / macOS 14 / Windows 11"
